spring.application.name=scaleup-backend

server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/scaleup_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:JoySit53}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

highlevel.base-url=https://services.leadconnectorhq.com

highlevel.internal-crm.location-id=${HIGHLEVEL_INTERNAL_CRM_LOCATION_ID:}
highlevel.internal-crm.token=${HIGHLEVEL_INTERNAL_CRM_TOKEN:}
highlevel.webhook.secret=${HIGHLEVEL_WEBHOOK_SECRET:}


# Internal CRM retry worker
crm.internal.retry.worker-delay-ms=60000